Router.route('/', {name: 'home', template: 'home'});
Router.route('/information',{name: 'information', template: 'information'})
Router.route('/profile');
Router.route('/tSurvey');
Router.route('/rateEmployer');
Router.route('/talentRegistration');
Router.route('/registerRep');
Router.route('/login');
Router.route('#');
Router.route('/employerInfo');
Router.route('/Emp');
Router.route('/success');
Router.route('/verify-email/:token');
Router.route('/about');
Router.route('/contact');
Router.route('/forgot');
Router.route('/changePassword');
Router.route('/match');
Router.route('/overview');
Router.route('rateEmployer2');
Router.route('rateEmployer3');
Router.route('rateEmployer4');
Router.route('educationView');
Router.route('skillsView');
Router.route('credsView');
Router.route('occupationView');
