Router.route('/', {name: 'home', template: 'home'});
Router.route('/information',{name: 'information', template: 'information'})
Router.route('/profile');
Router.route('/currentEmp');
Router.route('/formerEmp');
Router.route('/tSurvey');
Router.route('/rateEmployer');
Router.route('/rateFEmployer');
Router.route('/talentRegistration');
Router.route('/registerRep');
Router.route('/login');
Router.route('/rateWhich');
Router.route('/rateCurrentEmployerInfo');
Router.route('/rateFormerEmployerInfo');
Router.route('/employerInfo');
Router.route('/Emp');
Router.route('/success');
Router.route('/verify-email/:token');
Router.route('/about');
Router.route('/contact');
Router.route('/forgot');
Router.route('/changePassword');
